Removed linter check because it failed to start:
```
Run AbdulRehman-1/eslint-action@latest
  with:
    eslintrc: false
    extensions: js
    auto-fix-before-test: false
    annotations: true
    github-token: ***
    bin-path: node_modules/eslint/bin
Files changed.
Files for linting.
Rules to apply
/usr/local/bin/npm i eslint-config-airbnb --legacy-peer-deps

added 31 packages, and audited 32 packages in 2s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/usr/local/bin/node /home/runner/work/fibonacci-invariants-DojeeDev/fibonacci-invariants-DojeeDev/node_modules/eslint/bin/eslint code.js
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module '/home/runner/work/fibonacci-invariants-DojeeDev/fibonacci-invariants-DojeeDev/node_modules/eslint/bin/eslint'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.18.3
Error: The process '/usr/local/bin/node' failed with exit code 1
```